In [10]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

В переменной df содержатся данные такого вида
Отберите из них только те, где wealth принимает значение 'medium', а возраст составляет больше 35.
Поместите результат в переменную medium_35.

In [11]:
df = pd.DataFrame({'client_id': np.random.randint(1, 10000, 30),
                   'sex': np.random.choice([0, 1], 30),
                   'wealth': np.random.choice(['low', 'medium', 'high'], 30),
                   'age': np.random.randint(20, 70, 30)})

In [21]:
df.head()

   client_id  sex  wealth  age  older_than_30
0       5790    1  medium   66           True
1       7090    1    high   41           True
2       5297    1     low   55           True
3       3977    0  medium   28          False
4       8770    0  medium   21          False

In [15]:
medium_35 = df.loc[(df['wealth'] == 'medium') & (df['age'] > 35)]

Воспользуйтесь методом rename и приведите таблицу к более каноничному виду, сохранив её в ту же самую переменную df.

In [17]:
df_1 = df.rename(columns={'client_id': 'Клиент_id', 'sex': 'Пол', 'wealth': 'Благосостояние', 'age': 'Возраст'})

In [18]:
df_1.head()

   Клиент_id  Пол Благосостояние  Возраст
0       5790    1         medium       66
1       7090    1           high       41
2       5297    1            low       55
3       3977    0         medium       28
4       8770    0         medium       21

Добавьте в исследуемый нами датафрэйм df колонку older_than_30, в которой будет информация превышает ли значение переменной возраста 30 лет или нет (булево значение)`

In [20]:
df['older_than_30'] = df['age'] > 30

А теперь получите серию с числом уникальных значений для каждой колонки и присвойте её переменной unique_num.

In [24]:
unique_num = df.nunique()

In [25]:
unique_num

client_id        30
sex               2
wealth            3
age              24
older_than_30     2
dtype: int64

У нас появились новые данные! Переменная data хранит в себе датафрэйм следующего вида:
Проведите inner join датафрейма data с df из предыдущего шага, объединив их по колонке client_id, и поместите результат в переменную full_data (да, придумывать названия переменных иногда бывает сложно)
Предыдущий датафрейм загружен в переменную df, новый – в data

In [28]:
data = pd.DataFrame({'client_id': df.client_id.sample(10).values,
                   'amount': np.random.randint(1000, 100000, 10),
                   'date': np.random.randint(1585425000, 1585430000, 10)})

In [29]:
data.head()

   client_id  amount        date
0       6155   43052  1585429487
1       1350   94313  1585428593
2       6848   13281  1585427228
3       4464   22515  1585427510
4       6528   47439  1585425680

In [30]:
full_data = df.merge(data, on = 'client_id')

In [31]:
full_data.head()

   client_id  sex  wealth  age  older_than_30  amount        date
0       5297    1     low   55           True   90990  1585425523
1       8770    0  medium   21          False   67487  1585427208
2       1232    0    high   38           True   23950  1585425417
3       4464    1    high   23          False   22515  1585427510
4       6528    1    high   29          False   47439  1585425680

Теперь давайте создадим собственную функцию. Напишите функцию read_n_agg, которая:
1.	принимает на вход один параметр – путь к файлу
2.	при помощи переданного пути, считывает файл, в котором разделителем является ;
3.	считает средний заработок (income) по каждой компании (company), перенося колонку company в индекс (as_index=True)
4.	возвращает результат этих действий (агрегированный датафрэйм)
Данные выглядят вот так, скачать можно от.
P.S. Небольшое уточнение – менять что-то в данных или переименовывать колонки не нужно.
P.P.S. В задании надо указать только функцию, указывать конкретный путь к файлу не нужно. Он будет содержаться в аргументе функции внутри системы LMS!

In [ ]:
def read_n_agg(path):
    df = pd.read_csv(path, sep=';')
    return df.groupby('company').agg({'income': 'mean'})

Импортируйте pandas как pd. В данном задании ссылка на датасет находится в переменной path_to_file. 
Загрузите датасет, используя ; в качестве разделителя. 
Также укажите, что столбцы start_at, end_at, arrived_at нужно прочитать как даты (параметр parse_dates).
Результат запишите в переменную taxi.

In [6]:
df = pd.read_csv(r'C:\Users\PC\Desktop\Софт\Simulation\Simulation\data\3_taxi_peru.csv', encoding='windows-1251', sep=';')

In [8]:
df.head()

,journey_id,user_id,driver_id,taxi_id,icon,start_type,start_at,start_lat,start_lon,end_at,end_lat,end_lon,end_state,driver_start_lat,driver_start_lon,arrived_at,source,driver_score,rider_score
0,23a1406fc6a11d866e3c82f22eed4d4c,0e9af5bbf1edfe591b54ecdfd7e91e26,583949a89a9ee17d19e3ca4f137b6b4c,b12f4f09c783e29fe0d0ea624530db56,executive,asap,2010-11-16 16:44:00,"-12,13983536","-77,02355957",2010-11-16 17:29:00,"-12,05537033","-77,0413208",drop off,"-12,10825481","-77,0272739",2010-11-16 17:02:00,iPhone,5.0,5.0
1,dd2af4715d0dc16eded53afc0e243577,a553c46e3a22fb9c326aeb3d72b3334e,NaN,NaN,executive,asap,2010-06-01 00:34:00,"-12,13874817","-76,99536133",2010-06-01 00:37:00,"-12,12465668","-77,02886963",not found,NaN,NaN,NaN,iPhone,NaN,NaN
2,dd91e131888064bf7df3ce08f3d4b4ad,a553c46e3a22fb9c326aeb3d72b3334e,NaN,NaN,executive,asap,2010-05-31 05:01:00,"-12,12453079","-77,02780151",2010-05-31 05:04:00,"-12,13883209","-76,99530029",not found,NaN,NaN,NaN,iPhone,NaN,NaN
3,dd2af4715d0dc16eded53afc0e2466d0,a553c46e3a22fb9c326aeb3d72b3334e,NaN,NaN,executive,asap,2010-06-01 00:29:00,"-12,13885117","-76,99530029",2010-06-01 00:32:00,"-12,12458801","-77,02896118",not found,NaN,NaN,NaN,iPhone,NaN,NaN
4,85b7eabcf5d84e42dc7629b7d27781af,56772d544fdfa589a020a1ff894a86f7,d665fb9f75ef5d9cd0fd89479380ba78,0accdd3aa5a322f4129fa20b53278c69,executive,reserved,2010-09-11 23:55:00,"-12,08995438","-76,92626953",2010-09-12 01:07:00,"-12,02223206","-77,10638428",drop off,"-12,08311558","-76,9277072",2010-09-11 23:50:00,iPhone,4.0,5.0