Импортируйте библиотеку pandas как pd. Загрузите два датасета user_data и logs. Проверьте размер таблицы, типы переменных, посмотрите на описательную статистику. 
Вопрос: Сколько уникальных значений принимает переменная platform?

In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
user_data = pd.read_csv(r'C:\Users\PC\Desktop\Софт\Simulation\Simulation\data\3_user_data.csv')

In [3]:
logs = pd.read_csv(r'C:\Users\PC\Desktop\Софт\Simulation\Simulation\data\3_logs.csv')

In [5]:
user_data.head()

   client  premium  age
0   46346    False   58
1    4391    False   55
2   27372    False   64
3   11989    False   44
4   60664    False   49

In [26]:
logs.head()

   client  success  platform        time
0   40177     True     phone  1585412212
1   61468     True     phone  1585425658
2   35604    False     phone  1585459894
3    9961     True     phone  1585400189
4   10931     True  computer  1585468629

In [12]:
user_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2954 entries, 0 to 2953
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   client   2954 non-null   int64
 1   premium  2954 non-null   bool
 2   age      2954 non-null   int64
dtypes: bool(1), int64(2)
memory usage: 49.2 KB

In [11]:
logs.info()
logs.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   client    4500 non-null   int64
 1   success   4500 non-null   bool
 2   platform  4500 non-null   object
 3   time      4500 non-null   int64
dtypes: bool(1), int64(2), object(1)
memory usage: 110.0+ KB

              client success platform          time
count    4500.000000    4500     4500  4.500000e+03
unique           NaN       2        3           NaN
top              NaN    True    phone           NaN
freq             NaN    3289     2753           NaN
mean    50998.758000     NaN      NaN  1.585440e+09
std     28374.472495     NaN      NaN  2.314866e+04
min        40.000000     NaN      NaN  1.585400e+09
25%     27056.500000     NaN      NaN  1.585420e+09
50%     52659.000000     NaN      NaN  1.585440e+09
75%     76001.250000     NaN      NaN  1.585461e+09
max     99993.000000     NaN      NaN  1.585480e+09

Какой клиент совершил больше всего успешных операций?
Если несколько пользователей совершили одинаковое число успешных действий, перечислите их идентификаторы (client) через запятую и пробел в порядке возрастания. Например:
12, 123, 456

In [37]:
logs.loc[logs.success]\
    .groupby('client')\
    .agg({'success': 'count'})\
    .idxmax()

success    12179
dtype: int64

In [27]:
success_counts = logs.loc[logs.success].client.value_counts()

In [ ]:
max_num = success_counts.max()

In [38]:
max_success_users = success_counts.loc[success_counts == max_num]

In [40]:
max_success_users.index.sort_values()

Index([12179, 28719, 36165, 52870, 61468, 61473, 78349, 82563, 92584], dtype='int64', name='client')